/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(double_pulse_coalesce.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(103be2c37f63d3c40db3e07795c0a4a9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/dme/double_pulse_coalesce.h>
// pydoc.h is automatically generated in the build directory
#include <double_pulse_coalesce_pydoc.h>

void bind_double_pulse_coalesce(py::module& m)
{

    using double_pulse_coalesce = ::gr::dme::double_pulse_coalesce;


    py::class_<double_pulse_coalesce,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<double_pulse_coalesce>>(
        m, "double_pulse_coalesce", D(double_pulse_coalesce))

        .def(py::init(&double_pulse_coalesce::make),
             py::arg("min_distance"),
             py::arg("max_distance"),
             py::arg("delay"),
             D(double_pulse_coalesce, make))


        ;
}
