/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-dme
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_DME_API_H
#define INCLUDED_DME_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_dme_EXPORTS
#define DME_API __GR_ATTR_EXPORT
#else
#define DME_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_DME_API_H */
